{% set name = "parsac" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/BoldingBruggeman/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4445df224260bcd16f0d84d48e5a3e844350c9395ce3833b074390eb3340fc23

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - tqdm
    - netCDF4
    - salib
    - matplotlib-base

test:
  imports:
    - parsac
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/BoldingBruggeman/parsac
  summary: 'Parallel Sensitivity Analysis and Calibration'
  description: |
    parsac is a Python-based tool for sensitivity analysis and auto-calibration in parallel.
    It is designed for analysis of models that take significant time to run. For that reason,
    it focuses on storing and exploiting every single model result, and performing model
    runs in parallel on either a single machine or on computer clusters. It works with
    models that are run by calling one binary, that use YAML-based configuration files
    and that write their output to NetCDF.
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jornbr
