{% set name = "parsac" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/BoldingBruggeman/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e5b2fcd5b9c7632245141a41adf4158f0c5a63d35b5ef037ecb75c038d1e1fa6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - tqdm
    - netCDF4
    - salib
    - matplotlib-base

test:
  imports:
    - parsac
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/BoldingBruggeman/parsac
  summary: 'Parallel Sensitivity Analysis and Calibration'
  description: |
    parsac is a Python-based tool for sensitivity analysis and auto-calibration in parallel.
    It is designed for analysis of models that take significant time to run. For that reason,
    it focuses on storing and exploiting every single model result, and performing model
    runs in parallel on either a single machine or on computer clusters. It works with
    models that are run by calling one binary, that use YAML-based configuration files
    and that write their output to NetCDF.
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jornbr
